### ISSUE TITLE
Live Reload: Bind for 0.0.0.0:1025 failed: port is already allocated

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-mailpit#1]
Getting this error after hot reload need to figure out how to make Hot Reload work properly.

```
2023-10-13 14:53:28,969 INFO  [tc.axllent/mailpit:latest] (build-24) Container axllent/mailpit:latest is starting: 8b50a28a8723e8477e013591516d6c0f7a54a6c19d03f419f9c68066e91954e3
2023-10-13 14:53:29,111 ERROR [tc.axllent/mailpit:latest] (build-24) Could not start container [Error Occurred After Shutdown]: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint magical_jennings (9d8c6898914b0934f45ac05fa95fcf4939316374a6f64df7958928de6110d081): Bind for 0.0.0.0:1025 failed: port is already allocated"}

        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpit(MailpitProcessor.java:107)
        at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:60)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
```

**Comment by melloware** [comment]
@all-contributors add @melloware for code,maintenance
