### ISSUE TITLE
Error when running quarkus tests: Bind for 0.0.0.0:8025 failed: port is already allocated

### ISSUE THREAD

**Issue by erickloss** [quarkiverse/quarkus-mailpit#39]
Hello there,

when I run Quarkus tests via IntelliJ run-configuration or via Quarkus Continuous Testing, I get the error:

```
      └─ getTests() ✘ java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
               	[error]: Build step io.quarkiverse.mailpit.deployment.MailpitProcessor#startMailpitDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image axllent/mailpit:latest
               	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:81)
               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
               	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
               	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
               	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
               	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
               	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
               	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
               	at java.base/java.lang.Thread.run(Thread.java:833)
               	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
               Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image axllent/mailpit:latest
               	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:362)
               	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
               	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpit(MailpitProcessor.java:135)
               	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:72)
               	... 11 more
               Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
               	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
               	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
               	... 14 more
               Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
               	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:566)
               	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
               	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
               	... 15 more
               Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint festive_jepsen (9b72f35b4183c947da9a397790f13f615f91718b91e33a9739ce553fba29b247): Bind for 0.0.0.0:8025 failed: port is already allocated"}
            
               	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
               	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
               	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
               	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
               	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
               	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
               	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
               	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:455)
               	... 17 more
```

The test run does not seem to recognize, that the DevService is already started. I don't know if this is intentional behavior, I also might have an invalid configuration in my application.

It would also be great, if quarkus-mailpit would reuse existing containers. I dived into that by forking your repo and try to set the MailpitContainer to withReuse(true). But the running container is not recognized due to hash label mismatch.

Is there something that I am missing? How am I supposed to run a Test when the application is already running in local dev mode? My Idea would be:
1. Reuse the existing mailpit container during testing, or
2. Allow configuration for the exposed HTTP port (default: 8025), then I could set the port for testing to a different host port

I'am willed to contribute a PR if you can point me in the right direction.

Cheers
Eric

**Comment by melloware** [comment]
Thanks for the report!

@ggrebert you just helped me fix some of this in Quarkus Antivirus so I wonder if I am missing something here too with my Dev Service?

**Comment by melloware** [comment]
@all-contributors add @erickloss for bug

**Comment by melloware** [comment]
@erickloss i have never used continuous testing with Quarkus so I wonder if the Dev Service needs to be shut down between runs or whether its should know its already running and not have to restart for continuous testing?

**Comment by melloware** [comment]
i think i have another fix too @ggrebert but i wouldn't mind if you code reviewed and did your magic on this extension too.  Its very similar to Antivirus.  Th eissue here is its comparing two interfaces for equality same issue we ran into with Quinoa. I am fixing it now.

**Comment by melloware** [comment]
This issue was this: https://github.com/quarkiverse/quarkus-mailpit/commit/c173a40c823a619005966d61716c4bcbcdd0d73e

**Comment by erickloss** [comment]
Well that was fast, thank you very much for your reply.

> @erickloss i have never used continuous testing with Quarkus so I wonder if the Dev Service needs to be shut down between runs or whether its should know its already running and not have to restart for continuous testing?

I think in my particular case, it is independent of weather I run tests in continuous testing (which in my understanding **should not** start a new Quarkus instance by default) or if I use IntelliJ "play button".

The reason for that is: I use Cucumber / End-To-End tests which start a new instance of my application during the test execution anyway. My guess was, that when the container is reused via Testcontainers reuse logic, it should work by connecting to the existing mailpit container as if two applications would share the same mailpit service.

Regarding "shutting down between runs": That should only happen, when the `testcontainers.reuse.enable` is not  set to `true`, as for example the postgres dev service does.

I hope this helps understanding my use-case a bit better. I still don't know if im on the right track tbh ;)

I will try out 0.0.8 as soon as it is available on maven central. Thanks for your afford and work <3

Cheers

**Comment by erickloss** [comment]
PS: I use https://github.com/quarkiverse/quarkus-cucumber for cucumber integration.

**Comment by melloware** [comment]
OK something is failing the Quarkus release process so its holding up my deployments.

**Comment by melloware** [comment]
ok 0.0.8.1 is in Maven Central if you want to test it @erickloss

**Comment by erickloss** [comment]
I just tested it, the error still remains. I think this has to do with the cucumber setup, I'll investigate further.

**Comment by melloware** [comment]
ok let me know.

**Comment by erickloss** [comment]
<img width="929" alt="image" src="https://github.com/quarkiverse/quarkus-mailpit/assets/16836464/c42b1d96-9f58-43bb-85ab-f77ceb640305">
I debugged when quarkus runs its tests in continuous mode. It seems like the build step is called, even if the application already has started the dev services when run in the first place.

Is there a way to check if the dev service already exists?

I think this is how other extensions solve this problem:
https://github.com/quarkusio/quarkus/pull/19048/commits/8779c16582202fd19d3f56a1784bedf5c00760e3

**Comment by erickloss** [comment]
PS: the suspended thread in the screenshot above is:
<img width="525" alt="image" src="https://github.com/quarkiverse/quarkus-mailpit/assets/16836464/ab972c72-4763-4ee6-95fe-c7b5e0118d9b">

**Comment by ggrebert** [comment]
hi @erickloss ,
can you test the PR #44 if it fix your issue

**Comment by ggrebert** [comment]
you don't need to edit your properties anymore, they are overwritten by default

**Comment by erickloss** [comment]
I will test the PR tomorrow. Cheers

**Comment by melloware** [comment]
@all-contributors add @ggrebert for code,design

**Comment by erickloss** [comment]
@ggrebert the PR fixes the issue, thanks a lot!

**Comment by melloware** [comment]
I will release 0.0.9 tomorrow thanks @erickloss !!

**Comment by melloware** [comment]
0.0.9 is in Maven Central.

**Comment by erickloss** [comment]
It works like a charm. Thank you very much!

btw: the 0.0.9 also fixes a Bug that I encountered, where the Tests couldn't connect to the Mailpit container when run in **gitlab CI using docker-in-docker** (connection refused on the SMTP port). 
That works now as well with 0.0.9 <3

**Comment by melloware** [comment]
Fantastic news!
