### ISSUE TITLE
better exception when no mailers?

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-mailpit#55]
I added mailpit assuming it would "just work" but seems like it *requires* io.quarkus.mailer.* to be installed - thats at least how I read this exception I got:

```
2024-03-25 11:50:21,197 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.mailpit.deployment.MailpitProcessor#startMailpitDevService threw an exception: java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitContainer.getExposedConfig(MailpitContainer.java:108)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpit(MailpitProcessor.java:136)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:74)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.mailer.MailerName
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	... 14 more

	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:334)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:251)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:112)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:433)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.mailpit.deployment.MailpitProcessor#startMailpitDevService threw an exception: java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitContainer.getExposedConfig(MailpitContainer.java:108)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpit(MailpitProcessor.java:136)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:74)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.mailer.MailerName
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	... 14 more

	at io.quarkus.builder.Execution.run(Execution.java:123)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	... 9 more
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.NoClassDefFoundError: io/quarkus/mailer/MailerName
	at io.quarkiverse.mailpit.deployment.MailpitContainer.getExposedConfig(MailpitContainer.java:108)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpit(MailpitProcessor.java:136)
	at io.quarkiverse.mailpit.deployment.MailpitProcessor.startMailpitDevService(MailpitProcessor.java:74)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.mailer.MailerName
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:518)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
	... 14 more

```

a) if io.quarkus.mailer is a requirement should it not be a dependency?
b) if not a requirement shouild the exception be ignored or if required, inform the user that to fix this add io.quarkus.mailer rather than wall of noclassdeffounderror?

**Comment by melloware** [comment]
i think you are right it needs to be a dependency!  I just assumed people using mailpit would already have it but that is a bad assumption!

**Comment by melloware** [comment]
@all-contributors add @maxandersen for bugs
